fix base64-parsing of dns challenge
Previous error on dns challenge (maybe a python2 vs python3 issue?):
  File "./acme/helper.py", line 57, in b64_url_encode
    return encoded.rstrip("=")
TypeError: a bytes-like object is required, not 'str'

... so we give it, what it requests for:

return encoded.rstrip(b"=")